name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request: {}
  schedule:
      - cron: '0 * * * *'  # Update every hour
  workflow_dispatch:

jobs:
  build:
    if: (github.event_name == 'schedule' && github.repository == 'optuna/optunahub-web') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    permissions:
        contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name:
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.124.1'

      - name: Checkout Registry
        uses: actions/checkout@v4
        with:
          repository: optuna/optunahub-registry
          path: optunahub-registry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Prepare Contents
        run: python hugo_build.py

      - name: Build
        run: hugo --minify

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    if: (github.event_name == 'schedule' && github.repository == 'optuna/optunahub-web') || (github.event_name != 'schedule' && github.event_name != 'pull_request')
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
